name: Gettext updates
on:
  push:
    branches: main
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/gettext-template@master
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
        GIT_USER_NAME: "subhadeepjasu"
        GIT_USER_EMAIL: "subhajasu@gmail.com"
      with:
        translation_branch: 'main'